### ISSUE TITLE
Some 404 links

### ISSUE THREAD

**Issue by burnchar** [MarkPflug/Sylvan.AspNetCore#4]
On the [Sylvan.AspNetCore](https://github.com/MarkPflug/Sylvan.AspNetCore) page, all but the first two links are 404
For example, [Sylvan.AspNetCore.Http.Csv](https://github.com/MarkPflug/Sylvan.AspNetCore/blob/main/docs/Http.Csv.md).

**Comment by MarkPflug** [comment]
Added some minimal docs. Needs work still, but the links aren't broken at least.
